
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?autoReconnect=true&useSSL=false
    username: 
    password: 


